"""Synthetic UQ fixtures.

Builds named, fully-deterministic ``UQFixture`` instances that exercise the
input regimes our UQ models care about. One source of truth for "what does a
UQ test input look like" — used by the V0 equivalence one-shot today, and by
future V0/V1/V2 regime tests.

Each regime is a registered builder under the ``@regime("name")`` decorator;
``UQFixture.make(name, seed=0)`` is the public entry point.

Fingerprints are **fake** by design: random bit patterns generated by the
seeded RNG. They're shaped correctly for ``FingerprintProximity`` (bit-string
column on a DataFrame with ``id`` + ``target``), but they don't represent any
real chemistry — V0 doesn't use them, and V1/V2 regime tests are deferred
until we layer in real SMILES alongside (see DECISION 1 in the design notes).

Adding a regime: register it via ``@regime("my_regime")`` returning a
``UQFixture``. The builder gets the seed and an isolated RNG.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Dict, List

import numpy as np
import pandas as pd

# Matches workbench's Morgan default. Real chemistry would use radius=2 count
# fingerprints; we use binary bit-strings here because they're cheaper to
# generate and easier to read, and V0 ignores them anyway.
FP_NBITS = 2048


# ---------------------------------------------------------------------------
# UQFixture container
# ---------------------------------------------------------------------------
@dataclass
class UQFixture:
    """One regime of synthetic UQ inputs.

    Calibration side (``*_val``) and query side (``*_query``) are shape-aligned
    pairs. Proximity side is V1/V2 territory — V0 tests ignore it.

    Attributes:
        regime: Name of the regime that produced this fixture.
        y_true_val / y_pred_val / prediction_std_val / val_ids: Calibration
            set — what V0/V1 ``.fit(...)`` consumes.
        y_true_query / y_pred_query / prediction_std_query / query_ids: Held-out
            query set — what ``.predict(...)`` consumes. ``y_true_query`` is
            present so future coverage tests can compute empirical metrics; the
            V0 equivalence script doesn't need it.
        prox_df: DataFrame with columns ``id``, ``target``, ``fingerprint``
            (bit-string format expected by ``FingerprintProximity``). Used by
            V1/V2. For V0-only regimes this is still populated (random FPs) so
            V1/V2 can run on the same regime later — outputs just won't be
            meaningful.
        query_fingerprints: ``(n_query, FP_NBITS)`` bool array. Convenience
            view of the same bit strings ``prox_df`` carries, useful for
            building a query DataFrame in a V1/V2 test.
    """

    regime: str

    # Calibration set
    y_true_val: np.ndarray
    y_pred_val: np.ndarray
    prediction_std_val: np.ndarray
    val_ids: List[str]

    # Query set
    y_true_query: np.ndarray
    y_pred_query: np.ndarray
    prediction_std_query: np.ndarray
    query_ids: List[str]

    # Proximity backing (V1/V2 only — V0 ignores)
    prox_df: pd.DataFrame
    query_fingerprints: np.ndarray

    id_column: str = "id"
    target: str = "target"
    fingerprint_column: str = "fingerprint"

    # ---- public API ----
    @classmethod
    def make(cls, regime: str, seed: int = 0) -> "UQFixture":
        """Build a fixture by regime name. Deterministic given the seed."""
        if regime not in _REGIMES:
            available = ", ".join(sorted(_REGIMES))
            raise KeyError(f"Unknown regime '{regime}'. Available: {available}")
        return _REGIMES[regime](seed)

    @classmethod
    def available_regimes(cls) -> List[str]:
        """List all registered regime names, sorted alphabetically."""
        return sorted(_REGIMES)


# ---------------------------------------------------------------------------
# Registry & regime decorator
# ---------------------------------------------------------------------------
_REGIMES: Dict[str, Callable[[int], UQFixture]] = {}


def regime(name: str) -> Callable:
    """Register a regime builder under ``name``."""

    def _wrap(fn: Callable[[int], UQFixture]) -> Callable[[int], UQFixture]:
        if name in _REGIMES:
            raise ValueError(f"Regime '{name}' already registered")
        _REGIMES[name] = fn
        return fn

    return _wrap


# ---------------------------------------------------------------------------
# Helpers shared across regimes
# ---------------------------------------------------------------------------
def _ids(prefix: str, n: int) -> List[str]:
    """Generate sequential string IDs like 'val-0001'."""
    width = max(4, len(str(n)))
    return [f"{prefix}-{i:0{width}d}" for i in range(n)]


def _random_fingerprints(rng: np.random.Generator, n: int, density: float = 0.05) -> np.ndarray:
    """Generate ``n`` random binary fingerprints with the given bit density.

    Default density 5% mirrors real Morgan r=2 sparsity on small molecules.
    Returns a ``(n, FP_NBITS)`` bool array.
    """
    return rng.random((n, FP_NBITS)) < density


def _fingerprints_to_strings(fps: np.ndarray) -> List[str]:
    """Convert a (n, FP_NBITS) bool array to the bit-string format
    ``FingerprintProximity`` expects (no commas → binary, with commas → counts).
    """
    return ["".join("1" if b else "0" for b in row) for row in fps]


def _build_prox_df(
    rng: np.random.Generator,
    ids: List[str],
    targets: np.ndarray,
    density: float = 0.05,
) -> tuple[pd.DataFrame, np.ndarray]:
    """Build a ``prox_df`` with random fingerprints + the matching bool array.

    Returns:
        (prox_df, fingerprints_bool_array)
    """
    fps = _random_fingerprints(rng, len(ids), density=density)
    prox_df = pd.DataFrame(
        {
            "id": ids,
            "target": targets,
            "fingerprint": _fingerprints_to_strings(fps),
        }
    )
    return prox_df, fps


# ---------------------------------------------------------------------------
# Regime builders
# ---------------------------------------------------------------------------
@regime("well_calibrated")
def _well_calibrated(seed: int) -> UQFixture:
    """Honest base model: prediction_std ≈ actual error magnitude.

    Sanity floor — every UQ version should look reasonable here.
    """
    rng = np.random.default_rng(seed)
    n_val, n_query = 300, 100

    sigma_val = rng.uniform(0.2, 0.6, size=n_val)
    y_true_val = rng.normal(0, 2, size=n_val)
    y_pred_val = y_true_val + rng.normal(0, sigma_val)
    pred_std_val = sigma_val

    sigma_q = rng.uniform(0.2, 0.6, size=n_query)
    y_true_q = rng.normal(0, 2, size=n_query)
    y_pred_q = y_true_q + rng.normal(0, sigma_q)
    pred_std_q = sigma_q

    val_ids = _ids("val", n_val)
    query_ids = _ids("q", n_query)
    prox_df, _ = _build_prox_df(rng, val_ids, y_true_val)
    _, q_fps = _build_prox_df(rng, query_ids, y_true_q)

    return UQFixture(
        regime="well_calibrated",
        y_true_val=y_true_val,
        y_pred_val=y_pred_val,
        prediction_std_val=pred_std_val,
        val_ids=val_ids,
        y_true_query=y_true_q,
        y_pred_query=y_pred_q,
        prediction_std_query=pred_std_q,
        query_ids=query_ids,
        prox_df=prox_df,
        query_fingerprints=q_fps,
    )


@regime("overconfident")
def _overconfident(seed: int) -> UQFixture:
    """Reported std is much smaller than actual error magnitude.

    Calibrator should widen intervals (large conformal scale factors).
    """
    rng = np.random.default_rng(seed)
    n_val, n_query = 300, 100

    actual_sigma = rng.uniform(0.5, 1.0, size=n_val)
    reported_sigma_val = actual_sigma * 0.3
    y_true_val = rng.normal(0, 2, size=n_val)
    y_pred_val = y_true_val + rng.normal(0, actual_sigma)

    actual_sigma_q = rng.uniform(0.5, 1.0, size=n_query)
    reported_sigma_q = actual_sigma_q * 0.3
    y_true_q = rng.normal(0, 2, size=n_query)
    y_pred_q = y_true_q + rng.normal(0, actual_sigma_q)

    val_ids = _ids("val", n_val)
    query_ids = _ids("q", n_query)
    prox_df, _ = _build_prox_df(rng, val_ids, y_true_val)
    _, q_fps = _build_prox_df(rng, query_ids, y_true_q)

    return UQFixture(
        regime="overconfident",
        y_true_val=y_true_val,
        y_pred_val=y_pred_val,
        prediction_std_val=reported_sigma_val,
        val_ids=val_ids,
        y_true_query=y_true_q,
        y_pred_query=y_pred_q,
        prediction_std_query=reported_sigma_q,
        query_ids=query_ids,
        prox_df=prox_df,
        query_fingerprints=q_fps,
    )


@regime("underconfident")
def _underconfident(seed: int) -> UQFixture:
    """Reported std is much larger than actual error magnitude.

    Calibrator should narrow intervals (small conformal scale factors).
    """
    rng = np.random.default_rng(seed)
    n_val, n_query = 300, 100

    actual_sigma = rng.uniform(0.2, 0.4, size=n_val)
    reported_sigma_val = actual_sigma * 3.0
    y_true_val = rng.normal(0, 2, size=n_val)
    y_pred_val = y_true_val + rng.normal(0, actual_sigma)

    actual_sigma_q = rng.uniform(0.2, 0.4, size=n_query)
    reported_sigma_q = actual_sigma_q * 3.0
    y_true_q = rng.normal(0, 2, size=n_query)
    y_pred_q = y_true_q + rng.normal(0, actual_sigma_q)

    val_ids = _ids("val", n_val)
    query_ids = _ids("q", n_query)
    prox_df, _ = _build_prox_df(rng, val_ids, y_true_val)
    _, q_fps = _build_prox_df(rng, query_ids, y_true_q)

    return UQFixture(
        regime="underconfident",
        y_true_val=y_true_val,
        y_pred_val=y_pred_val,
        prediction_std_val=reported_sigma_val,
        val_ids=val_ids,
        y_true_query=y_true_q,
        y_pred_query=y_pred_q,
        prediction_std_query=reported_sigma_q,
        query_ids=query_ids,
        prox_df=prox_df,
        query_fingerprints=q_fps,
    )


@regime("heteroskedastic")
def _heteroskedastic(seed: int) -> UQFixture:
    """Error magnitude scales with |prediction|.

    V0's per-bin isotonic should outperform a flat conformal — different bins
    pick up different std → |residual| slopes.
    """
    rng = np.random.default_rng(seed)
    n_val, n_query = 400, 120

    y_true_val = rng.uniform(-5, 5, size=n_val)
    # Sigma grows with |y|
    actual_sigma = 0.1 + 0.4 * np.abs(y_true_val)
    y_pred_val = y_true_val + rng.normal(0, actual_sigma)
    pred_std_val = actual_sigma  # well-reported

    y_true_q = rng.uniform(-5, 5, size=n_query)
    actual_sigma_q = 0.1 + 0.4 * np.abs(y_true_q)
    y_pred_q = y_true_q + rng.normal(0, actual_sigma_q)
    pred_std_q = actual_sigma_q

    val_ids = _ids("val", n_val)
    query_ids = _ids("q", n_query)
    prox_df, _ = _build_prox_df(rng, val_ids, y_true_val)
    _, q_fps = _build_prox_df(rng, query_ids, y_true_q)

    return UQFixture(
        regime="heteroskedastic",
        y_true_val=y_true_val,
        y_pred_val=y_pred_val,
        prediction_std_val=pred_std_val,
        val_ids=val_ids,
        y_true_query=y_true_q,
        y_pred_query=y_pred_q,
        prediction_std_query=pred_std_q,
        query_ids=query_ids,
        prox_df=prox_df,
        query_fingerprints=q_fps,
    )


@regime("biased")
def _biased(seed: int) -> UQFixture:
    """Systematic prediction offset (model adds 0.5 to every prediction).

    q_50 should track the offset prediction, not the truth — the calibrator
    can't undo bias, only widen intervals to cover it. Useful for confirming
    we don't *correct* the bias by accident.
    """
    rng = np.random.default_rng(seed)
    n_val, n_query = 300, 100
    bias = 0.5

    sigma_val = rng.uniform(0.3, 0.6, size=n_val)
    y_true_val = rng.normal(0, 2, size=n_val)
    y_pred_val = y_true_val + bias + rng.normal(0, sigma_val)
    pred_std_val = sigma_val

    sigma_q = rng.uniform(0.3, 0.6, size=n_query)
    y_true_q = rng.normal(0, 2, size=n_query)
    y_pred_q = y_true_q + bias + rng.normal(0, sigma_q)
    pred_std_q = sigma_q

    val_ids = _ids("val", n_val)
    query_ids = _ids("q", n_query)
    prox_df, _ = _build_prox_df(rng, val_ids, y_true_val)
    _, q_fps = _build_prox_df(rng, query_ids, y_true_q)

    return UQFixture(
        regime="biased",
        y_true_val=y_true_val,
        y_pred_val=y_pred_val,
        prediction_std_val=pred_std_val,
        val_ids=val_ids,
        y_true_query=y_true_q,
        y_pred_query=y_pred_q,
        prediction_std_query=pred_std_q,
        query_ids=query_ids,
        prox_df=prox_df,
        query_fingerprints=q_fps,
    )


@regime("out_of_distribution_queries")
def _ood_queries(seed: int) -> UQFixture:
    """Cal targets in [-1, 1]; query targets in [4, 6].

    V0 has no way to flag this (no proximity); V1/V2 should — useful regime
    for future AD-sensitivity tests, harmless for V0 equivalence.
    """
    rng = np.random.default_rng(seed)
    n_val, n_query = 300, 80

    sigma_val = rng.uniform(0.2, 0.4, size=n_val)
    y_true_val = rng.uniform(-1, 1, size=n_val)
    y_pred_val = y_true_val + rng.normal(0, sigma_val)
    pred_std_val = sigma_val

    # Queries land far from the cal-set support
    sigma_q = rng.uniform(0.2, 0.4, size=n_query)
    y_true_q = rng.uniform(4, 6, size=n_query)
    y_pred_q = y_true_q + rng.normal(0, sigma_q)
    pred_std_q = sigma_q

    val_ids = _ids("val", n_val)
    query_ids = _ids("q", n_query)
    prox_df, _ = _build_prox_df(rng, val_ids, y_true_val)
    _, q_fps = _build_prox_df(rng, query_ids, y_true_q)

    return UQFixture(
        regime="out_of_distribution_queries",
        y_true_val=y_true_val,
        y_pred_val=y_pred_val,
        prediction_std_val=pred_std_val,
        val_ids=val_ids,
        y_true_query=y_true_q,
        y_pred_query=y_pred_q,
        prediction_std_query=pred_std_q,
        query_ids=query_ids,
        prox_df=prox_df,
        query_fingerprints=q_fps,
    )


@regime("activity_cliff_queries")
def _activity_cliff_queries(seed: int) -> UQFixture:
    """Query predictions match cal-set predictions, but query truths diverge.

    V0 can't detect this. V1/V2 would need real fingerprint engineering to
    test (close in FP space, divergent target) — placeholder for now using
    matched preds/truths. Behavior should still be valid for V0 equivalence.
    """
    rng = np.random.default_rng(seed)
    n_val, n_query = 300, 80

    sigma_val = rng.uniform(0.2, 0.4, size=n_val)
    y_true_val = rng.normal(0, 1, size=n_val)
    y_pred_val = y_true_val + rng.normal(0, sigma_val)
    pred_std_val = sigma_val

    # Queries: predictions look fine, but actual truth is shifted ("cliff")
    sigma_q = rng.uniform(0.2, 0.4, size=n_query)
    y_pred_q = rng.normal(0, 1, size=n_query)
    y_true_q = y_pred_q + rng.normal(2.0, 0.3, size=n_query)  # cliff!
    pred_std_q = sigma_q

    val_ids = _ids("val", n_val)
    query_ids = _ids("q", n_query)
    prox_df, _ = _build_prox_df(rng, val_ids, y_true_val)
    _, q_fps = _build_prox_df(rng, query_ids, y_true_q)

    return UQFixture(
        regime="activity_cliff_queries",
        y_true_val=y_true_val,
        y_pred_val=y_pred_val,
        prediction_std_val=pred_std_val,
        val_ids=val_ids,
        y_true_query=y_true_q,
        y_pred_query=y_pred_q,
        prediction_std_query=pred_std_q,
        query_ids=query_ids,
        prox_df=prox_df,
        query_fingerprints=q_fps,
    )


@regime("bin_edge_queries")
def _bin_edge_queries(seed: int) -> UQFixture:
    """y_pred_val ~ Uniform(0, 10), so V0's 10 quantile bins land near
    integers 1, 2, ..., 9. Query predictions are set EXACTLY to those values,
    catching any off-by-one or strict-vs-loose inequality bug in V0's bin
    lookup.
    """
    rng = np.random.default_rng(seed)
    n_val = 300

    # Sample y_pred uniformly so bin edges are predictable
    y_pred_val = rng.uniform(0, 10, size=n_val)
    actual_sigma = rng.uniform(0.2, 0.5, size=n_val)
    y_true_val = y_pred_val - rng.normal(0, actual_sigma)
    pred_std_val = actual_sigma

    # Query predictions exactly at expected bin edges
    edges = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])
    y_pred_q = np.repeat(edges, 6)  # 9 edges * 6 queries each = 54 queries
    n_query = len(y_pred_q)
    pred_std_q = np.full(n_query, 0.3)
    # y_true at the query is irrelevant for V0 equivalence; pick something
    y_true_q = y_pred_q + rng.normal(0, 0.3, size=n_query)

    val_ids = _ids("val", n_val)
    query_ids = _ids("q", n_query)
    prox_df, _ = _build_prox_df(rng, val_ids, y_true_val)
    _, q_fps = _build_prox_df(rng, query_ids, y_true_q)

    return UQFixture(
        regime="bin_edge_queries",
        y_true_val=y_true_val,
        y_pred_val=y_pred_val,
        prediction_std_val=pred_std_val,
        val_ids=val_ids,
        y_true_query=y_true_q,
        y_pred_query=y_pred_q,
        prediction_std_query=pred_std_q,
        query_ids=query_ids,
        prox_df=prox_df,
        query_fingerprints=q_fps,
    )


@regime("tiny_calibration_set")
def _tiny_calibration_set(seed: int) -> UQFixture:
    """Only 30 cal rows — every bin should fall below ``MIN_SAMPLES_PER_BIN=20``,
    so every bin's isotonic falls back to the global fit. Tests V0's
    small-sample fallback path.
    """
    rng = np.random.default_rng(seed)
    n_val, n_query = 30, 40

    sigma_val = rng.uniform(0.2, 0.5, size=n_val)
    y_true_val = rng.normal(0, 1, size=n_val)
    y_pred_val = y_true_val + rng.normal(0, sigma_val)
    pred_std_val = sigma_val

    sigma_q = rng.uniform(0.2, 0.5, size=n_query)
    y_true_q = rng.normal(0, 1, size=n_query)
    y_pred_q = y_true_q + rng.normal(0, sigma_q)
    pred_std_q = sigma_q

    val_ids = _ids("val", n_val)
    query_ids = _ids("q", n_query)
    prox_df, _ = _build_prox_df(rng, val_ids, y_true_val)
    _, q_fps = _build_prox_df(rng, query_ids, y_true_q)

    return UQFixture(
        regime="tiny_calibration_set",
        y_true_val=y_true_val,
        y_pred_val=y_pred_val,
        prediction_std_val=pred_std_val,
        val_ids=val_ids,
        y_true_query=y_true_q,
        y_pred_query=y_pred_q,
        prediction_std_query=pred_std_q,
        query_ids=query_ids,
        prox_df=prox_df,
        query_fingerprints=q_fps,
    )
