"""Feature preparation: column hygiene shared by AWS and local FeatureSet creation.

Both ingest paths run the same prep so a FeatureSet built locally has the same
columns, names, and dtypes as one built in AWS. The AWS-only steps (event_time,
Feature Group definitions) stay with the AWS transform.
"""

import logging
import re

import pandas as pd

# Workbench Imports
from workbench.utils.datetime_utils import datetime_to_iso8601

log = logging.getLogger("workbench")

# Columns AWS generates that are never features
AWS_COLUMNS = ["write_time", "api_invocation_time", "is_deleted", "event_time"]


def sanitize_column_name(name: str) -> str:
    """Replace invalid characters in a column name.

    Args:
        name (str): The column name to sanitize

    Returns:
        str: The sanitized column name
    """
    sanitized = re.sub("[^a-zA-Z0-9-_]", "_", name)
    sanitized = re.sub("_+", "_", sanitized)
    sanitized = sanitized.strip("_")

    if sanitized != name:
        log.info(f"Sanitizing {name} to {sanitized}")

    return sanitized


def shorten_column_name(name: str, max_length: int = 20) -> str:
    """Shorten a column name by dropping leading underscore-delimited parts.

    Args:
        name (str): The column name to shorten
        max_length (int): Maximum length of the result (default: 20)

    Returns:
        str: The shortened column name
    """
    if len(name) <= max_length:
        return name

    # Start building the new name from the end
    parts = name.split("_")[::-1]
    new_name = ""
    for part in parts:
        if len(new_name) + len(part) + 1 <= max_length:  # +1 for the underscore
            new_name = f"{part}_{new_name}" if new_name else part
        else:
            break

    # If new_name is empty, just use the last part of the original name
    if not new_name:
        new_name = parts[0]

    log.info(f"Shortening {name} to {new_name}")
    return new_name


def process_column_name(column: str, shorten: bool = False) -> str:
    """Make a column name safe for FeatureSet storage.

    Args:
        column (str): The column name to process
        shorten (bool): Shorten the column name (default: False)

    Returns:
        str: The processed column name
    """
    column = sanitize_column_name(column)
    if shorten:
        column = shorten_column_name(column)
    return column


def convert_columns_to_categorical(df: pd.DataFrame, columns: list, skip_columns: list = None) -> pd.DataFrame:
    """Convert low-cardinality columns to the Categorical dtype.

    Args:
        df (pd.DataFrame): The DataFrame to process
        columns (list): Columns to consider for conversion
        skip_columns (list, optional): Columns to leave alone (id/event_time)

    Returns:
        pd.DataFrame: The DataFrame with converted columns
    """
    skip_columns = skip_columns or []
    for feature in columns:
        if feature in skip_columns:
            continue
        unique_values = df[feature].nunique()
        if 1 < unique_values < 10:
            log.important(f"Converting column {feature} to categorical (unique {unique_values})")
            df[feature] = df[feature].astype("category")
        else:
            log.warning(f"Column {feature} too many unique values {unique_values} skipping...")
    return df


def one_hot_encode(df: pd.DataFrame, one_hot_columns: list, skip_columns: list = None) -> pd.DataFrame:
    """One-hot encode categorical columns, with column name management.

    Args:
        df (pd.DataFrame): The DataFrame to process
        one_hot_columns (list): The columns to one-hot encode
        skip_columns (list, optional): Columns never converted to categorical (id/event_time)

    Returns:
        pd.DataFrame: The DataFrame with one-hot encoded columns
    """
    # Grab the current list of columns
    current_columns = list(df.columns)

    # Now convert the list of columns into Categorical and then One-Hot Encode
    df = convert_columns_to_categorical(df, one_hot_columns, skip_columns=skip_columns)
    log.important(f"One-Hot encoding columns: {one_hot_columns}")
    df = pd.get_dummies(df, columns=one_hot_columns)

    # Compute the new columns generated by get_dummies
    new_columns = list(set(df.columns) - set(current_columns))
    log.important(f"New columns generated: {new_columns}")

    # Convert new columns to int32
    df[new_columns] = df[new_columns].astype("int32")

    # For the new columns we're going to shorten the names
    renamed_columns = {col: process_column_name(col) for col in new_columns}
    df.rename(columns=renamed_columns, inplace=True)

    return df


def convert_column_types(df: pd.DataFrame) -> pd.DataFrame:
    """Convert DataFrame columns to types compatible with SageMaker Feature Store.

    Feature Store supports only three scalar types: Integral, Fractional, String.
    Everything else gets coerced:
      - bool / nullable boolean -> int32, or float64 if NAs are present (Integral/Fractional)
      - category                -> str          (String)
      - datetime                -> ISO-8601 str (String)
      - pandas nullable Int/Float -> numpy int/float (or float64 if Int has NAs).
        SageMaker V3's load_feature_definitions_from_dataframe() only recognizes
        numpy dtypes, not pandas nullable dtypes. See
        https://github.com/aws/sagemaker-python-sdk/issues/5675

    Args:
        df (pd.DataFrame): The DataFrame to convert

    Returns:
        pd.DataFrame: The DataFrame with converted column types
    """
    # Bool -> Integral (or Fractional if NAs are present)
    for column in df.select_dtypes(include=["bool", "boolean"]).columns:
        col = df[column]
        df[column] = col.astype("float64" if col.isna().any() else "int32")

    # Category -> String
    for column in df.select_dtypes(include="category").columns:
        df[column] = df[column].astype("str")

    # Datetime -> String (ISO-8601)
    for column in df.select_dtypes(include="datetime").columns:
        df[column] = df[column].map(datetime_to_iso8601).astype("string")

    # Pandas nullable numeric -> numpy equivalent (float64 fallback for Int with NAs)
    for column in df.columns:
        dtype = df[column].dtype
        if pd.api.types.is_extension_array_dtype(dtype) and dtype.kind in "iuf":
            col = df[column]
            if dtype.kind in "iu" and col.isna().any():
                df[column] = col.astype("float64")
            else:
                df[column] = col.astype(str(dtype).lower())

    return df


def ensure_id_column(df: pd.DataFrame, id_column: str) -> tuple[pd.DataFrame, str]:
    """Ensure the DataFrame has an id column, generating one if requested.

    Args:
        df (pd.DataFrame): The DataFrame to check
        id_column (str): The id column name (None/"auto" generates an "auto_id" column)

    Returns:
        tuple[pd.DataFrame, str]: The DataFrame and the resolved id column name

    Raises:
        ValueError: If the named id column isn't in the DataFrame
    """
    if id_column in [None, "auto"]:
        log.warning("Generating an 'auto_id' column, we highly recommended setting the 'id_column'")
        df["auto_id"] = df.index
        return df, "auto_id"

    if id_column not in df.columns:
        error_msg = f"Id column {id_column} not found in the DataFrame"
        log.critical(error_msg)
        raise ValueError(error_msg)

    return df, id_column


def prep_dataframe(
    df: pd.DataFrame,
    id_column: str,
    event_time_column: str = None,
    one_hot_columns: list = None,
) -> tuple[pd.DataFrame, str]:
    """Run the shared FeatureSet column prep on a DataFrame.

    Drops AWS-generated columns, one-hot encodes, lowercases and de-duplicates
    column names, ensures an id column, drops any 'training' column, and coerces
    dtypes to the Feature Store type set.

    Args:
        df (pd.DataFrame): The DataFrame to prepare
        id_column (str): The id column (None/"auto" generates an "auto_id" column)
        event_time_column (str, optional): Event time column, protected from categorical conversion
        one_hot_columns (list, optional): Columns to one-hot encode

    Returns:
        tuple[pd.DataFrame, str]: The prepared DataFrame and the resolved id column name

    Raises:
        ValueError: If duplicate column names are detected
    """
    log.info("Prep the dataframe (cat_convert, convert types, and lowercase columns)...")

    # Remove any columns generated from AWS
    df = df.drop(columns=AWS_COLUMNS, errors="ignore")

    # If one-hot columns are provided then one-hot encode them
    if one_hot_columns:
        df = one_hot_encode(df, one_hot_columns, skip_columns=[event_time_column, id_column])

    # Ensure all column names are strings
    if not all(isinstance(c, str) for c in df.columns):
        log.warning("Non-string column names detected, converting to strings...")
        df.columns = [str(c) for c in df.columns]

    # Convert columns names to lowercase, Athena will not work with uppercase column names
    if str(df.columns) != str(df.columns.str.lower()):
        for c in df.columns:
            if c != c.lower():
                log.important(f"Column name {c} converted to lowercase: {c.lower()}")
        df.columns = df.columns.str.lower()

    # The id reference follows the frame's columns down to lowercase
    if id_column not in [None, "auto"]:
        id_column = id_column.lower()

    # Check for duplicate column names in the dataframe
    if len(df.columns) != len(set(df.columns)):
        log.critical("Duplicate column names detected in the DataFrame")
        duplicates = df.columns[df.columns.duplicated()].tolist()
        log.critical(f"Duplicated columns: {duplicates}")
        raise ValueError("Duplicate column names detected in the DataFrame")

    # Make sure we have the required id column
    df, id_column = ensure_id_column(df, id_column)

    # The 'training' column is a model-training concern, not FeatureSet data
    if "training" in df.columns:
        log.important("Dropping 'training' column (train/val splits are handled at model training)")
        df = df.drop(columns=["training"])

    # Coerce to the Feature Store type set
    df = convert_column_types(df)

    return df, id_column
