#!/usr/bin/env python

import webbrowser
from app import app


def start_dashboard():
    """Open a browser and start the Dash app"""
    url = "http://localhost:8000"
    webbrowser.open(url)

    # Note: This 'main' is purely for running/testing locally
    # app.run_server(host="0.0.0.0", port=8000, debug=True)
    app.run_server(host="0.0.0.0", port=8000)


if __name__ == "__main__":
    """Run our web application in TEST mode"""
    start_dashboard()
